name: Generate TTS languages data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 06 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Generate data
        env:
          GITHUB_GENERATOR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate:tts-languages

      - name: Upload data
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ttsLanguages
          path: |
            ./_data/ttsLanguages.json
          if-no-files-found: error
          retention-days: 1

  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download data
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: "ttsLanguages"
          path: "./_data/"

      - name: Create PR
        id: pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update TTS languages data"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          title: "Update TTS languages data"
          body: |
            This PR was automatically generated by the workflow.
            It updates the TTS languages data.
          base: main
          branch: update-tts-languages-data
          add-paths: |
            _data/ttsLanguages.json